### ISSUE TITLE
적 잡고 나면 돈 주는거에 시각적 피드백

### ISSUE THREAD

**Issue by KBluePurple** [Team-Vamos/Project-Eddy#46]
+10G
나 돈 같은걸 직관적으로 표시해주는 표시 있으면 좋을듯

**Comment by pmj0704** [comment]
100개 -> 100(광석 아이콘)

**Comment by pmj0704** [comment]
또 이슈 그 노랑색 지금 돈이 노랑색인데 아이콘(보라색)이랑 같이 띄우면 색이 안맞아 노랑 색으로 연보라로 바꾸자

**Comment by KBluePurple** [comment]
해결됨
